# @package _group_
user: ${env:USER}
#workspace: ${env:WORK}
#tempdir: ${env:JOBSCRATCH}
engine: "SLURM"
directive: "#SBATCH"
#account: ${env:ACCOUNT}
cleanup: "module purge"
cmd: "sbatch"
#launchers: ["single_gpu_16g", "single_gpu_32g", "multi_gpu", "single_gpu"]
launchers: "single_gpu_16g"
# NOTE: to be launched directly on the access node!
node: null 
#conda_path: "${cluster.workspace}/miniconda3/etc/profile.d/conda.sh"
shell:
  bin_path: "/usr/bin/bash"
  config_path: "~/.bashrc"
conda_env: ${env:CONDA_DEFAULT_ENV}
